spring:
  cache:
    type: redis
    cache-names: redis-cache
  data:
    redis:
      host: localhost
      port: 6379
      password: cGFzc3dvcmQ=
  datasource:
    url: jdbc:postgresql://localhost:5432/tasklist
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
      continue-on-error: false
#      data-locations: classpath:demo_data.sql
  liquibase:
    change-log: classpath:liquibase/db.changelog.yaml
    enabled: true
    default-schema: tasklist
security:
  jwt:
    secret: c2VjcmV0LWJhc2U2NGFzZGFzZGFkYXNkYXNkYXNkd3F3YzMvQDNjY2FzZA==
    access: 3600000
    refresh: 86400000

server:
  port: 8080
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: tasklist.tasklist.domain
