spring:
  config:
    import: optional:file:.env[.properties]
  cache:
    type: redis
    cache-names: redis-cache
  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379
      password: ${REDIS_PASSWORD}
  datasource:
    url: jdbc:postgresql://${DB_HOST}:5432/${DB_DATABASE}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:liquibase/db.changelog.yaml
    enabled: true
    default-schema: public
security:
  jwt:
    secret: ${JWT_SECRET}
    access: 1
    refresh: 30
server:
  port: 8080
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: tasklist.tasklist.domain
